### ISSUE TITLE
master does not compile: undefined: strings in policyreportprinter.go

### ISSUE THREAD

**Issue by 1PoPTRoN** [kubescape/kubescape#3549]
# Description

`master` is currently broken at HEAD — `go build ./...` fails for everyone.

`core/pkg/resultshandling/printer/v2/policyreportprinter.go` uses `strings.Builder`, `strings.ToLower` and `strings.TrimRight` (lines 326, 332, 346, 360, 387) but the `strings` import was removed from the import block (lines 3-19). This blocks every PR build, every local `make build`, and the release pipeline until fixed.

This happened because two PRs landed ~20s apart without a rebase:

* **#3470** added the sanitizers `sanitizeDNS1123Subdomain` / `sanitizeLabelValue` which need `strings`.
* **#3492** centralized output path handling via `printer.ResolveOutputFile` and removed the only `strings` usage it could see in `SetWriter`, so it dropped the import. On its own base it was correct, but on the merged result it deleted an import the other PR just started needing.

Git doesn't flag this — it's a semantic merge conflict, not a textual one.

# Environment
OS: any (reproduced on macOS 14 + Ubuntu 22.04 LTS)
Version: `master` at HEAD after #3492 (commit `371f4aaf`) — `kubescape version` does not build to run

# Steps To Reproduce

1. `git clone https://github.com/kubescape/kubescape && cd kubescape`
2. `git checkout master && git pull`
3. `go build ./...`

# Expected behavior

`go build ./...`, `go vet ./...` and `golangci-lint run ./...` should succeed. The `policyreport` printer should compile and the `sanitizeDNS1123Subdomain` / `sanitizeLabelValue` helpers should be available for `policyReportName` and `policyReportLabels`.

# Actual Behavior

```
# github.com/kubescape/kubescape/v4/core/pkg/resultshandling/printer/v2
core/pkg/resultshandling/printer/v2/policyreportprinter.go:325:8: undefined: strings
core/pkg/resultshandling/printer/v2/policyreportprinter.go:331:20: undefined: strings
core/pkg/resultshandling/printer/v2/policyreportprinter.go:345:9: undefined: strings
core/pkg/resultshandling/printer/v2/policyreportprinter.go:359:8: undefined: strings
core/pkg/resultshandling/printer/v2/policyreportprinter.go:386:9: undefined: strings
```

No binary is produced. CI `a-pr-scanner.yaml` (unit tests, goreleaser build, smoke_testing, golangci-lint) fails before any tests run.

# Additional context

**File:** `core/pkg/resultshandling/printer/v2/policyreportprinter.go:3-19` (import block), used at `:326`, `:332`, `:346`, `:360`, `:387`.

**Suggested fix:**

Add `strings` back to the import block (stdlib group, alphabetically between `sort` and `time` — `goimports` order), no logic change:

```go
import (
	"context"
	"fmt"
	"os"
	"sort"
	"strings"
	"time"
	// ...
)
```

This is the same fix as #3503. The one-line import restore is the safest path — it re-enables the existing `policyreportprinter_test.go` coverage (`TestPolicyReportName_SanitizesClusterAndNamespace`, `TestPolicyReportLabels_SanitizesClusterLabelValue`, etc.) which already exercise all five `strings.*` paths but couldn't compile on broken master.

**To prevent this class of bug:** enable branch protection `Require branches to be up-to-date before merging` + a required `go build ./...` / `golangci-lint` check on the merge commit. That forces a build of the *combined* result, which is the only place this conflict is visible.

**Comment by 1PoPTRoN** [comment]
Update: as noted in https://github.com/kubescape/kubescape/pull/3550#pullrequestreview-5015410352, this build break (5x `undefined: strings` after #3470 + #3492, reproduces on `371f4aaf`) was already restored on `master` by #3503 and #3508 before this branch was cut (PR #3550 base `f8a16618`/`76cf9a5f` already contains the import). 

PR #3550 is now rebased and retitled to a **comment-only guard** (`chore: clarify strings import dependency`) so the history is accurate — no live build failure remains. This issue can be closed as superseded by #3503/#3508, or kept linked to #3550 for the guard — happy to close per maintainer preference.
