### ISSUE TITLE
[ LFX 2026 ] SecurityException CRD's `expiresAt` CEL validation rule uses `now()`, which does not exist in Kubernetes CEL and the CRD fails to install

### ISSUE THREAD

**Issue by yugal07** [kubescape/kubescape#2400]
# Description

`kubescape/deploy/crd/security-exception-crd.yaml` carries a CEL transition rule (added in PR #2244) that tries to enforce *"`expiresAt` must be in the future when newly set or changed"*:

```yaml
spec:
  type: object
  x-kubernetes-validations:
    - rule: >-
        !has(self.expiresAt)
        || (oldSelf.hasValue() && has(oldSelf.value().expiresAt) && oldSelf.value().expiresAt == self.expiresAt)
        || timestamp(self.expiresAt) > now()
      optionalOldSelf: true
      message: "expiresAt must be in the future when newly set or changed"
```

This rule **cannot compile**. Kubernetes CRD validation CEL deliberately does **not** expose a current-time function there is no `now()` (nor any equivalent) available to `x-kubernetes-validations`. Wall-clock time is excluded on purpose because validation must be deterministic and re-evaluable (e.g. on no-op updates, re-admission, storage migration). As a result, the apiserver rejects the entire CRD at install time, so the CRD can never be created from this file.

This went unnoticed because the file is an **orphan**: nothing in the kubescape repo references `deploy/crd/security-exception-crd.yaml` (no Makefile target, no embed, no test, no kustomization). It is never applied during CI or install, so its CEL was never compiled by a real apiserver. The CRDs that actually ship live in **helm-charts** (`charts/kubescape-operator/crds/{security-exception,cluster-security-exception}.crd.yaml`) and did **not** contain this rule, so installs succeeded masking the defect.

## How this was found

While implementing CRD-level CEL validation for the SecurityException feature (kubescape/kubescape#1982), I went to mirror the `expiresAt` rule from #2244 into the shipping helm-charts CRDs. Running a server-side dry-run against a live **v1.31.0** apiserver surfaced the failure immediately:

```
$ kubectl apply --dry-run=server -f charts/kubescape-operator/crds/security-exception.crd.yaml
The CustomResourceDefinition "securityexceptions.kubescape.io" is invalid:
* spec...x-kubernetes-validations[0].rule: compilation failed:
    ERROR: <input>:1:161: undeclared reference to 'now' (in container '')
 | ... || timestamp(self.expiresAt) > now()
 | ...............................^
* spec...x-kubernetes-validations[0].optionalOldSelf: Invalid value: true:
    may not be set if oldSelf is not used in rule
```

(The second error is a knock-on: because the rule fails to compile, the apiserver never registers that `oldSelf` was used, so `optionalOldSelf: true` is also flagged.)

The same dry-run with `now()` removed and only time-free rules present (e.g. "at least one of `vulnerabilities`/`posture`", "`justification` required when `status: not_affected`") compiles and applies cleanly — confirming `now()` is the sole blocker.

# Environment
- OS: `Ubuntu 24.04` (Linux 6.17)
- Kubernetes apiserver: `v1.31.0`
- Source: `kubescape/deploy/crd/security-exception-crd.yaml` at `main` HEAD (rule introduced by PR #2244)

# Steps To Reproduce
1. `kubectl apply --dry-run=server -f kubescape/deploy/crd/security-exception-crd.yaml`
2. Observe `compilation failed: undeclared reference to 'now'` and the CRD is rejected.
3. Remove the `timestamp(self.expiresAt) > now()` rule; re-run — the CRD now compiles and applies.

# Expected behavior
- The shipped/reference CRD installs on any supported apiserver.
- If future-time enforcement of `expiresAt` is desired, it is implemented with a mechanism that *can* access request time, not CRD CEL.

# Actual Behavior
- The CRD containing the `now()` rule is rejected at creation time on every apiserver, so the file is uninstallable.
- The defect is invisible in normal use only because the file is an orphan that is never applied (the real CRDs ship from helm-charts without this rule).

# Source
- `kubescape/deploy/crd/security-exception-crd.yaml` (lines ~33–39)  the `x-kubernetes-validations` block with `timestamp(self.expiresAt) > now()`; introduced by PR #2244.
- This file is referenced nowhere in the repo (orphan)  `grep -rn "security-exception-crd\|deploy/crd" kubescape/` returns no Go/YAML/Makefile hits — which is why the broken CEL was never exercised.
- Shipping CRDs that should stay free of this rule: `helm-charts/charts/kubescape-operator/crds/security-exception.crd.yaml` and `cluster-security-exception.crd.yaml`.
- Context: discovered while adding cross-field CEL validation for SecurityException (kubescape/kubescape#1982). The two time-free rules (at-least-one-of `vulnerabilities`/`posture`; `justification` required when `not_affected`) were verified to compile and enforce correctly on v1.31.0; only the `now()` rule fails.

**Comment by yugal07** [comment]
@matthyx Would value your intake on this. 

The rule itself can't be made to work in CRD CEL (there's genuinely no now() / request-time access in x-kubernetes-validations it's excluded for determinism), so this isn't a "fix the expression" situation. The deeper issue is that deploy/crd/security-exception-crd.yaml is an orphan: nothing in the repo references it (no Go, YAML, Makefile, or CI). deploy/ exists only for this one file, and it's already drifted from the CRDs we actually ship in helm-charts (it carries this broken rule, and it's missing the ClusterSecurityException CRD entirely).

I'm thinking we just remove it rather than repair it, consolidate on the helm-charts CRDs as the single source of truth. I've already added the two enforceable cross-field rules there (justification-required-when-not_affected and at-least-one-of vulnerabilities/posture), verified compiling + enforcing on a v1.31 apiserver. The "expiresAt in the future" constraint stays documented-only for v1beta1; if we ever want it enforced at admission, it'd need a ValidatingAdmissionPolicy (which can see request time)

If you'd rather keep a repo-local CRD copy around (e.g. as an envtest fixture), I'm happy to instead sync it to the helm version drop the now() rule, add the two working rules, and add the missing cluster CRD. Either way, the broken rule goes. What's your preference?

**Comment by matthyx** [comment]
@yugal07 thanks for the thorough writeup and the dry-run evidence. Agreed on your first option: **delete `deploy/crd/security-exception-crd.yaml`** and treat the helm-charts CRDs as the single source of truth.

The reasoning is sound — `now()`/request-time isn't available in CRD `x-kubernetes-validations` CEL (excluded by design so validation stays re-evaluable on no-op updates and re-admission), so the rule can't be repaired in place. And the file is a true orphan that's already drifted (broken rule, missing the ClusterSecurityException CRD), so a hand-synced repo-local copy would just be ongoing drift-debt with no consumer. No need for an envtest fixture today; if we want one later we can generate it from the helm-charts source.

The two enforceable cross-field rules you already added there (justification-required-when-`not_affected`, at-least-one-of `vulnerabilities`/`posture`) are the right scope for CRD CEL. Let's keep the `expiresAt`-in-the-future constraint documented-only for v1beta1 — and if we ever enforce it, the natural place is the operator that already evaluates exceptions (treat an expired exception as inactive at evaluation time), rather than admission CEL.

Please go ahead and open the PR removing the file.
